### PR TITLE
add noop executer in bless function

### PR DESCRIPTION
**Pull request by aslansky**
When I tried to do something like `Fireproof.bless(Promise)` `var promise = new newQ();`failed because it seems the executor function is mandatory when using the core-js implementation.

Giving an empty function to the constructor fixes that.

### CODE REVIEW

**Comment by urish** [comment]
:+1:

**Comment by urish** [comment]
The current implementation (i.e. calling `new newQ();` without a callback) also fails on Firefox

**Comment by zloirock** [comment]
> seems the executor function is mandatory

It's a correct behavior by the spec, [step 2](http://www.ecma-international.org/ecma-262/6.0/#sec-promise-executor).

**Comment by daguej** [comment]
Closes #13

**Pull request merged**
